#!/usr/bin/env bash
#
# create_db.sh - initial FROST setup created with docker.
#
# 1) Creates sta_archive + sta_partage (if missing) + PostGIS.
# 2) Creates a NOSUPERUSER PostgreSQL role for the API, with just what it needs:
#      - CRUD (SELECT/INSERT/UPDATE/DELETE) on the FROST tables,
#      - ownership of "OBSERVATIONS" (required by the code's for DISABLE TRIGGER),
# 3) Starts the FROST containers (docker compose up -d), waits for FROST to
#    create the tables, then finalises the grants (OBSERVATIONS ownership).
#
# -> no need to run the script twice. Idempotent (safe to re-run).
# Pass --no-frost to NOT start FROST (if you manage it separately): in that
# case, re-run the script after FROST's first start to finalise the grants.
#
# Credentials are entered at the keyboard (nothing is hard-coded). 
# The superuser account is used only by this script (and FROST),
# the API uses only the least-privileged role.
#
# From those prompts this script GENERATES two local, gitignored files:
#   ../.env.api  -> least-privilege role credentials, read by the API (run.py)
#   ./.env       -> Postgres credentials of the CONTAINERS, read by docker compose
#
# Optional overrides: PGHOST PGPORT PGUSER API_ROLE DB_ARCHIVE DB_PARTAGE DOCKER_COMPOSE
#
set -euo pipefail

export PGHOST="${PGHOST:-127.0.0.1}"
export PGPORT="${PGPORT:-5433}"
export PGUSER="${PGUSER:-postgres}"          # admin superuser (owns FROST)
DB_ARCHIVE="${DB_ARCHIVE:-sta_archive}"
DB_PARTAGE="${DB_PARTAGE:-sta_partage}"
API_ROLE="${API_ROLE:-sofair_api}"           # least-privilege role of the API
DC="${DOCKER_COMPOSE:-sudo docker compose}"

START_FROST=1
[ "${1:-}" = "--no-frost" ] && START_FROST=0

# --- Interactive credential prompts ---
read -rsp "PostgreSQL superuser password (${PGUSER}@${PGHOST}:${PGPORT}): " SUPER_PW; echo
read -rp  "Least-privilege API role name [${API_ROLE}]: " _r; API_ROLE="${_r:-$API_ROLE}"
read -rsp "Password to set for the API role (${API_ROLE}): " API_PW; echo
[ -n "$SUPER_PW" ] || { echo "Empty superuser password, aborting."; exit 1; }
[ -n "$API_PW" ]   || { echo "Empty API role password, aborting."; exit 1; }
export PGPASSWORD="$SUPER_PW"

# escape single quotes for SQL literals
esc() { printf "%s" "$1" | sed "s/'/''/g"; }
API_PW_SQL="$(esc "$API_PW")"

# Grant logic shared with reset_db.sh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=_grant_api.sh
source "$SCRIPT_DIR/_grant_api.sh"


case "$SUPER_PW" in
    *\'*)
        echo "❌ The superuser password contains an apostrophe ('), which Docker"
        echo "   Compose's .env format cannot represent."
        echo "   Change that password in PostgreSQL, or write frost/.env by hand."
        exit 1 ;;
esac

ENV_COMPOSE="$SCRIPT_DIR/.env"
{
    echo "# Generated by frost/create_db.sh LOCAL file, never committed."
    echo "# Read by docker compose to interpolate docker-compose.yaml."
    echo "POSTGRES_USER='${PGUSER}'"
    echo "POSTGRES_PASSWORD='${SUPER_PW}'"
    echo "POSTGRES_HOST='${POSTGRES_HOST:-host.docker.internal}'"
    echo "POSTGRES_PORT='${PGPORT}'"
} > "$ENV_COMPOSE"
chmod 600 "$ENV_COMPOSE"
echo "  • frost/.env generated (FROST container credentials, chmod 600)"

ensure_db() {
    local db="$1"
    if [ "$(psql -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$db'")" = "1" ]; then
        echo "  • database '$db': already present"
    else
        psql -d postgres -c "CREATE DATABASE $db;" >/dev/null
        echo "  • database '$db': created"
    fi
    psql -d "$db" -c "CREATE EXTENSION IF NOT EXISTS postgis;" >/dev/null
    echo "    └ postgis extension OK"
}

echo "== FROST databases =="
ensure_db "$DB_ARCHIVE"
ensure_db "$DB_PARTAGE"

echo "== Least-privilege API role: ${API_ROLE} (NOSUPERUSER) =="
psql -d postgres -v ON_ERROR_STOP=1 >/dev/null <<SQL
DO \$\$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='${API_ROLE}') THEN
    ALTER ROLE "${API_ROLE}" LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '${API_PW_SQL}';
  ELSE
    CREATE ROLE "${API_ROLE}" LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '${API_PW_SQL}';
  END IF;
END
\$\$;
SQL

# Base grants BEFORE startup: FROST will create the tables with CRUD
# auto-applied to the API role (ALTER DEFAULT PRIVILEGES).
echo "== Base grants for the API role =="
grant_api_base "$DB_ARCHIVE"
grant_api_base "$DB_PARTAGE"
echo "  • CRUD grants (future tables) applied on both databases"

if [ "$START_FROST" -eq 1 ]; then
    echo "== Starting FROST =="
    ( cd "$SCRIPT_DIR" && $DC up -d )
    echo "== Finalising grants (waiting for the tables) =="
    for db in "$DB_ARCHIVE" "$DB_PARTAGE"; do
        if wait_for_observations "$db"; then
            grant_api_tables "$db"
            echo "  • $db: CRUD + OBSERVATIONS ownership applied"
        else
            echo "  ⚠️  $db: OBSERVATIONS not created yet (timeout). Re-run this script once FROST is ready."
        fi
    done
else
    echo "== FROST not started (--no-frost) =="
    for db in "$DB_ARCHIVE" "$DB_PARTAGE"; do
        if grant_api_tables "$db"; then
            echo "  • $db: CRUD + OBSERVATIONS ownership applied (tables present)"
        else
            echo "  • $db: tables missing -> start FROST then re-run this script"
        fi
    done
fi

# --- Writes the API role credentials to a local, gitignored file ---
# (auto-loaded by run.py, or 'source .env.api'). NEVER committed.
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_API="$ROOT_DIR/.env.api"
q="'"
API_PW_SQ=${API_PW//$q/$q\\$q$q}   # escape ' for a single-quoted shell literal
{
    echo "# API database credentials (least-privilege role). Generated by frost/create_db.sh."
    echo "# LOCAL file, never committed. Auto-loaded by run.py, or: source .env.api"
    echo "export STALT_DB_USER=${API_ROLE}"
    echo "export STALT_DB_PASSWORD='${API_PW_SQ}'"
    echo "export STALT_DB_HOST=${PGHOST}"
    echo "export STALT_DB_PORT=${PGPORT}"
} > "$ENV_API"
chmod 600 "$ENV_API"

echo
echo "✅ Done."
echo "   API credentials written to ${ENV_API} (chmod 600, not committed)."
echo "   The API loads them automatically on startup (python run.py)."
echo "   Container credentials written to ${ENV_COMPOSE} (chmod 600)."
echo "   -> ./restart_frost.sh, ./stop_frost.sh and ./reset_db.sh reuse them."
