#!/usr/bin/env bash
#
# delete_db.sh - TOTAL REMOVAL, to start over from scratch.
#
# Stops FROST, then DELETES both databases (sta_archive + sta_partage) AND the
# least-privilege API role. Recreates nothing: to rebuild, run create_db.sh.
#
# ⚠️ A PostgreSQL role is a CLUSTER-level object: a plain DROP DATABASE does not
#    remove it. So we drop the databases FIRST (which releases the OBSERVATIONS
#    ownership and the role's grants), THEN the role.
#
# ⚠️ Destructive and irreversible. Confirmation "DELETE" required (unless -y/--yes).
#    Pass --keep-role to keep the API role.
#
# Optional overrides:
#   PGHOST PGPORT PGUSER PGPASSWORD API_ROLE DB_ARCHIVE DB_PARTAGE DOCKER_COMPOSE
#
set -euo pipefail

export PGHOST="${PGHOST:-127.0.0.1}"
export PGPORT="${PGPORT:-5433}"
export PGUSER="${PGUSER:-postgres}"          # admin superuser
API_ROLE="${API_ROLE:-sofair_api}"           # least-privilege API role
DB_ARCHIVE="${DB_ARCHIVE:-sta_archive}"
DB_PARTAGE="${DB_PARTAGE:-sta_partage}"
DC="${DOCKER_COMPOSE:-sudo docker compose}"

ASSUME_YES=0
KEEP_ROLE=0
for arg in "$@"; do
    case "$arg" in
        -y|--yes)     ASSUME_YES=1 ;;
        --keep-role)  KEEP_ROLE=1 ;;
    esac
done

# Superuser password typed at the keyboard (nothing hard-coded)
if [ -z "${PGPASSWORD:-}" ]; then
    read -rsp "PostgreSQL superuser password (${PGUSER}@${PGHOST}:${PGPORT}): " PGPASSWORD; echo
    export PGPASSWORD
fi

cd "$(dirname "$0")"   # directory holding docker-compose.yaml

# Warning only: this script merely runs `down`, which does not need valid
# credentials. (frost/.env is generated by create_db.sh.)
[ -f .env ] || echo "⚠️  frost/.env missing (generated by ./create_db.sh): stopping anyway."

if [ "$ASSUME_YES" -ne 1 ]; then
    echo "⚠️  TOTAL REMOVAL (irreversible):"
    echo "      - database $DB_ARCHIVE"
    echo "      - database $DB_PARTAGE"
    [ "$KEEP_ROLE" -eq 1 ] && echo "      - API role '$API_ROLE': KEPT (--keep-role)" \
                           || echo "      - API role '$API_ROLE': DELETED"
    read -r -p "Type DELETE (uppercase) to confirm: " answer
    if [ "$answer" != "DELETE" ]; then
        echo "Cancelled."
        exit 1
    fi
fi

echo "→ Stopping the FROST containers..."
$DC down

echo "→ Dropping the databases..."
psql -d postgres -c "DROP DATABASE IF EXISTS $DB_ARCHIVE WITH (FORCE);" >/dev/null
psql -d postgres -c "DROP DATABASE IF EXISTS $DB_PARTAGE WITH (FORCE);" >/dev/null
echo "  ✓ databases dropped"

if [ "$KEEP_ROLE" -ne 1 ]; then
    echo "→ Dropping the API role '$API_ROLE'..."
    # The databases are already dropped -> no owned objects nor per-database grants left.
    if psql -d postgres -v ON_ERROR_STOP=1 -c "DROP ROLE IF EXISTS \"$API_ROLE\";" >/dev/null 2>&1; then
        echo "  ✓ role dropped"
    else
        echo "  ⚠️  could not drop '$API_ROLE' (remaining dependencies in another database?)."
        echo "     In each affected database: DROP OWNED BY \"$API_ROLE\";  then re-run."
    fi
fi

echo
echo "✅ Everything removed. To start over: ./create_db.sh"
