#!/usr/bin/env bash
#
# reset_db.sh - WIPES both FROST databases clean (archive + partage).
#
# Chains: stop FROST -> DROP + CREATE both databases (+ PostGIS) -> restart
# FROST (which recreates the tables EMPTY). Erases EVERYTHING: Things, Sensors,
# Datastreams AND Observations.
#
# ⚠️ Destructive and irreversible. Asks for an explicit confirmation (type YES),
#    unless -y / --yes is passed.
#
# Also re-applies the grants of the least-privilege API role (wiped by the DROP
# DATABASE): CRUD before the FROST restart, OBSERVATIONS ownership after.
#
# Optional overrides:
#   PGHOST PGPORT PGUSER PGPASSWORD API_ROLE DB_ARCHIVE DB_PARTAGE DOCKER_COMPOSE
#
set -euo pipefail

export PGHOST="${PGHOST:-127.0.0.1}"
export PGPORT="${PGPORT:-5433}"
export PGUSER="${PGUSER:-postgres}"          # admin superuser
API_ROLE="${API_ROLE:-sofair_api}"           # least-privilege API role (already created by create_db.sh)
DB_ARCHIVE="${DB_ARCHIVE:-sta_archive}"
DB_PARTAGE="${DB_PARTAGE:-sta_partage}"
DC="${DOCKER_COMPOSE:-sudo docker compose}"

# Grant logic shared with create_db.sh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=_grant_api.sh
source "$SCRIPT_DIR/_grant_api.sh"

# Superuser password typed at the keyboard (nothing hard-coded; an already
# exported PGPASSWORD is honoured)
if [ -z "${PGPASSWORD:-}" ]; then
    read -rsp "PostgreSQL superuser password (${PGUSER}@${PGHOST}:${PGPORT}): " PGPASSWORD; echo
    export PGPASSWORD
fi

# Move into the script's directory (where docker-compose.yaml lives)
cd "$(dirname "$0")"

# frost/.env holds the Postgres credentials Compose interpolates into
# docker-compose.yaml. It is GENERATED by create_db.sh, never written by hand.
# Hard stop here: this script brings FROST back up ($DC up -d), and without
# those values the containers would restart with an empty connection URL.
[ -f .env ] || {
    echo "❌ frost/.env is missing: run ./create_db.sh first (it generates the file)."
    exit 1
}

ASSUME_YES=0
if [ "${1:-}" = "-y" ] || [ "${1:-}" = "--yes" ]; then
    ASSUME_YES=1
fi

if [ "$ASSUME_YES" -ne 1 ]; then
    echo "⚠️  This will DELETE all data from the databases:"
    echo "      - $DB_ARCHIVE   (${PGUSER}@${PGHOST}:${PGPORT})"
    echo "      - $DB_PARTAGE   (${PGUSER}@${PGHOST}:${PGPORT})"
    echo "    Things, Sensors, Datastreams AND Observations will be lost."
    read -r -p 'Type YES (uppercase) to confirm: ' answer
    if [ "$answer" != "YES" ]; then
        echo "Cancelled."
        exit 1
    fi
fi

echo "→ Stopping the FROST containers..."
$DC down

reset_db() {
    local db="$1"
    echo "→ Resetting '$db'..."
    psql -d postgres -c "DROP DATABASE IF EXISTS $db WITH (FORCE);" >/dev/null
    psql -d postgres -c "CREATE DATABASE $db;" >/dev/null
    psql -d "$db" -c "CREATE EXTENSION IF NOT EXISTS postgis;" >/dev/null
    echo "  ✓ '$db' recreated (empty, postgis OK)"
}

reset_db "$DB_ARCHIVE"
reset_db "$DB_PARTAGE"

# Base grants BEFORE the restart: FROST will recreate the tables with CRUD
# auto-applied to the API role (ALTER DEFAULT PRIVILEGES).
echo "→ Base grants for the API role (${API_ROLE})..."
grant_api_base "$DB_ARCHIVE"
grant_api_base "$DB_PARTAGE"

echo "→ Restarting FROST (recreating the empty tables)..."
$DC up -d

# OBSERVATIONS ownership AFTER FROST has recreated the tables.
echo "→ Waiting for FROST to recreate the tables, then finalising grants..."
for db in "$DB_ARCHIVE" "$DB_PARTAGE"; do
    if wait_for_observations "$db"; then
        grant_api_tables "$db"
        echo "  ✓ $db: CRUD + OBSERVATIONS ownership re-applied to role ${API_ROLE}"
    else
        echo "  ⚠️  $db: OBSERVATIONS not created yet (timeout). Re-run ./create_db.sh once FROST is ready."
    fi
done

echo "✅ Reset complete (data wiped, grants of role ${API_ROLE} re-applied)."
echo "   curl -s 'http://localhost:8081/FROST-Server/v1.1/Things?\$count=true'   # archive"
echo "   curl -s 'http://localhost:8080/FROST-Server/v1.1/Things?\$count=true'   # partage"
echo "   (@iot.count should be 0)"
