#!/usr/bin/env bash
#
# stop_frost.sh - stops the FROST containers (archive + partage).
#
# Deletes NO data: the PostgreSQL databases live on the host, not inside the
# containers. `docker compose down` only stops/removes the containers.
#
# Optional override: DOCKER_COMPOSE (e.g. "docker compose" without sudo).
#
set -euo pipefail

DC="${DOCKER_COMPOSE:-sudo docker compose}"
cd "$(dirname "$0")"   # directory holding docker-compose.yaml


[ -f .env ] || echo "⚠️  frost/.env missing (generated by ./create_db.sh): stopping anyway."

echo "→ Stopping the FROST containers..."
$DC down
echo "✅ FROST stopped (the PostgreSQL data on the host is untouched)."
